# -*- coding: utf-8 -*-
"""UnemploymentAnalysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1buluvHb1XenE8bSDbq9tMtmjKVXMAWh4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

#reading csv file
df = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")
#printing first five rows
df.head()

#printing last five rows
df.tail()

df.shape

df.info()

#checking for null values
df.isnull().sum()

df.describe()

df.columns

df.columns=["States"," Date", " Frequency", "Estimated Unemployment Rate", "Estimated Employed", " Estimated Labour Participation Rate","Region", "longitude", "latitude"]
df

df.dtypes

df.nunique()

plt.figure(figsize=(20,20))
sns.heatmap(data=df.corr(), annot=True, cmap='Greens')

sns.pairplot(df, size=4)

#plot a boxplot
plt.figure(figsize=(20,20))
df.boxplot()

unemployment=df[["States","Region","Estimated Unemployment Rate"]]
figure=px.sunburst(unemployment,path=["Region","States"],
                   values="Estimated Unemployment Rate",
                   width=800,
                   height=800,
                   title="Unemployment Rate In India")
figure.show()